AI_CHATBOT_ORIGINS = {
    "ChatGPT": "USA",
    "Bard": "USA",
    "Gemini": "USA",
    "Claude": "USA",
    "Perplexity": "USA",
    "Pi": "USA",
    "Replika": "USA",
    "Character AI": "USA",
    "ChatSonic": "India",
    "YouChat": "USA",
    "Mitsuku": "UK",
    "Kuki": "UK",
    "Cleverbot": "UK",
    "Jasper": "USA",
    "HuggingChat": "USA/France",
    "Janitor AI": "International",
    "Tavern AI": "Open Source / USA",
    "Poe": "USA",
    "Kajiwoto": "USA",
    "Soulmate AI": "USA",
    "AI Girlfriend": "Unknown",
    "Myanima": "Unknown",
    "DreamGF": "International",
    "SoulFun": "Unknown",
    "SpicyChat AI": "International",
    "ChatFAI": "Malta",
    "Anima AI": "UK",
    "Botify AI": "USA",
    "GPT Girlfriend": "USA",
    "Candy AI": "Malta / USA",
    "Eva AI": "USA",
    "AIClover": "South Korea",
    "Kindroid": "USA",
    "AI Friend": "Unknown",
    "Slutbot": "USA",
    "Forever Voices": "USA",
    "Kupid AI": "USA",
    "Baidu Ernie Bot": "China",
    "Microsoft Xiaoice": "China",
    "Yandex Alisa": "Russia",
    "Samsung Bixby": "South Korea",
    "Apple Siri": "USA",
    "Google Assistant": "USA",
    "Amazon Alexa": "USA",
    "Meta AI": "USA",
    "Snapchat My AI": "USA",
    "Chai": "USA",
    "Woebot": "USA",
    "Wysa": "India",
    "Elomia": "Ukraine",
    "SimSimi": "South Korea",
    "GigaChat": "Russia",
    "Inflection Pi": "USA",
    "Nomi AI": "USA",
    "Paradot": "Hong Kong",
    "Venus Chub AI": "International",
    "Blush": "USA",
    "OurDream AI": "International",
    "AIAllure": "International",
    "SillyTavern": "Open Source / International",
    "AI Dungeon": "USA",
    "NovelAI": "USA / Japan",
    "Fables.gg": "USA",
    "Moescape": "Japan",
    "Caryn AI": "USA",
    "Personal AI": "USA",
    "HeraHaven": "USA",
    "Deepseek Chat": "China",
    "Blackbox AI": "USA",
    "Talkie AI": "USA",
    "HiWaifu": "USA",
    "Moemate": "USA",
    "Friend (Avi Schiffmann)": "USA"
}

from difflib import get_close_matches

def get_chatbot_origin(chatbot_name: str) -> str:
    chatbot_name = chatbot_name.strip()
    if chatbot_name in AI_CHATBOT_ORIGINS:
        return AI_CHATBOT_ORIGINS[chatbot_name]
    close = get_close_matches(chatbot_name, AI_CHATBOT_ORIGINS.keys(), n=1, cutoff=0.8)
    if close:
        return AI_CHATBOT_ORIGINS[close[0]]
    return "Unknown"
