# Auto-generated AI keyword list for CATDAMS
AI_KEYWORDS = [
    "01.ai",
    "ai boyfriend",
    "ai chat partner",
    "ai companion",
    "ai emotional support",
    "ai friend",
    "ai friendship",
    "ai girlfriend",
    "ai intimacy",
    "ai lover",
    "ai mental health chatbot",
    "ai partner",
    "ai relationship",
    "ai romance",
    "ai roleplay",
    "ai therapy chatbot",
    "anima ai",
    "anthropic",
    "auto-gpt",
    "babyagi",
    "baichuan ai",
    "bard",
    "candy ai",
    "character.ai",
    "chatglm",
    "chatgpt",
    "charstar ai",
    "claude",
    "cohere",
    "crushon.ai",
    "deepseek",
    "deepwisdom",
    "digital girlfriend",
    "doubao",
    "dreambf.ai",
    "dreamgf.ai",
    "ernie bot",
    "evatalk",
    "falcon",
    "foresight ai",
    "gemini",
    "gemma ai",
    "google palm",
    "gpt-3.5",
    "gpt-4",
    "grok ai",
    "groq",
    "hiwaifu",
    "hornywinko",
    "hyperbrain",
    "iflytek spark",
    "inflection ai",
    "joyhoonga",
    "kajiwoto",
    "kindroid",
    "kimi",
    "kobold ai",
    "llama",
    "llamaindex",
    "love chatbot",
    "meta ai",
    "minimax",
    "mistral",
    "moemate",
    "moonshot ai",
    "muah",
    "myedit",
    "nastia ai",
    "nsfw chatbot",
    "openai",
    "perplexity",
    "pi ai",
    "prompt engineering",
    "prompt injection",
    "qwen",
    "replika",
    "relationship simulator",
    "roleplay chatbot",
    "sensechat",
    "skylark2",
    "sparkdesk",
    "suxxaflirt",
    "synthetic relationship",
    "talkie",
    "talkie ai",
    "tigerbot",
    "virtual companion",
    "virtual partner",
    "virtual soulmate",
    "x.ai",
    "xiaobing",
    "xiaoice",
    "you.com",
    "yuanbao",
    "zhiniao ai",
    "zhipu ai",
]
