# Deploy CATDAMS FastAPI app to Azure App Service using GitHub Actions and OIDC

name: Build and deploy Python app to Azure Web App - catdams-app-MV

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Run tests here
      # - name: Run tests
      #   run: pytest

      - name: Zip app for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB4788810B554699965908630A445B7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA504F789F9F41DAAF170A638E879D1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4719683F69154E129A611EA9FF6A0BAF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'catdams-app-MV'
          slot-name: 'Production'
          package: release.zip
          deployment-method: runFromPackage
